sudo: false
language: node_js
cache:
  directories:
  - bower_components
  - node_modules
env:
  global:
  - GH_REF=github.com/in-or-out/inorout-ui.git
after_success:
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master" && ./build.sh dist /inorout-ui || echo "Pull request. Skipping build" >&2
- test "$TRAVIS_PULL_REQUEST" = "false" && test "$TRAVIS_BRANCH" = "master" && ./deploy.sh dist || echo "Pull request. Skipping deployment" >&2
